global:
  environment: local

kong:
  proxy:
    type: LoadBalancer
    loadBalancerIP: "172.18.255.200"
  admin:
    type: LoadBalancer
    loadBalancerIP: "172.18.255.201"

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 1Gi
  grafana:
    persistence:
      enabled: true
      size: 1Gi

argo-cd:
  redis:
    persistence:
      enabled: true
      size: 1Gi
  server:
    persistence:
      enabled: true
      size: 1Gi

vault:
  server:
    dataStorage:
      size: 1Gi
    auditStorage:
      size: 1Gi
